"""Add Skill and ExchangeOffer models

Revision ID: 483922186970
Revises: 850f324dd0cb
Create Date: 2025-06-24 02:52:48.677348

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "483922186970"
down_revision = "850f324dd0cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_challenge_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("associated_skill_id", sa.Integer(), nullable=True),
        sa.Column(
            "challenge_type",
            sa.Enum(
                "TEXT_RESPONSE",
                "PHOTO_UPLOAD",
                "CHECKBOX_COMPLETION",
                name="challengetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevel"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_name"), ["name"], unique=True)

    op.create_table(
        "exchange_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("offered_skill_id", sa.Integer(), nullable=False),
        sa.Column("desired_skill_id", sa.Integer(), nullable=True),
        sa.Column("desired_description", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "MATCHED", "COMPLETED", "CANCELLED", name="offerstatusenum"
            ),
            nullable=False,
        ),
        sa.Column("location_preference", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["desired_skill_id"],
            ["skill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["offered_skill_id"],
            ["skill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exchange_offer", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exchange_offer_desired_skill_id"),
            ["desired_skill_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exchange_offer_offered_skill_id"),
            ["offered_skill_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exchange_offer_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_challenge_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_template_id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("user_response", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING_REVIEW", "COMPLETED", "FAILED", name="completionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_template_id"],
            ["practice_challenge_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_challenge_completions")
    with op.batch_alter_table("exchange_offer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exchange_offer_user_id"))
        batch_op.drop_index(batch_op.f("ix_exchange_offer_offered_skill_id"))
        batch_op.drop_index(batch_op.f("ix_exchange_offer_desired_skill_id"))

    op.drop_table("exchange_offer")
    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_name"))

    op.drop_table("skill")
    op.drop_table("practice_challenge_templates")
    # ### end Alembic commands ###
