"""Add journal, mindset challenge, and mindful moment models

Revision ID: d91ae988d469
Revises: 850f324dd0cb
Create Date: 2025-06-24 02:57:51.320756

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d91ae988d469"
down_revision = "850f324dd0cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mindful_moment_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mindset_challenge_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum("DAILY", "WEEKLY", "ONE_TIME", name="mindsetchallengefrequency"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "practice_challenge_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("associated_skill_id", sa.Integer(), nullable=True),
        sa.Column(
            "challenge_type",
            sa.Enum(
                "TEXT_RESPONSE",
                "PHOTO_UPLOAD",
                "CHECKBOX_COMPLETION",
                name="challengetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevel"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("reflection_tags", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_challenge_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_template_id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("user_response", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING_REVIEW", "COMPLETED", "FAILED", name="completionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_template_id"],
            ["practice_challenge_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_mindset_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_template_id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("user_reflection", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "SKIPPED", name="mindsetcompletionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_template_id"],
            ["mindset_challenge_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_reminder_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("mindful_moment_template_id", sa.Integer(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "SPECIFIC_TIME",
                name="mindfulmomentreminderfrequency",
            ),
            nullable=False,
        ),
        sa.Column("time_of_day", sa.Time(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mindful_moment_template_id"],
            ["mindful_moment_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_reminder_settings")
    op.drop_table("user_mindset_completions")
    op.drop_table("user_challenge_completions")
    op.drop_table("journal_entries")
    op.drop_table("practice_challenge_templates")
    op.drop_table("mindset_challenge_templates")
    op.drop_table("mindful_moment_templates")
    # ### end Alembic commands ###
