"""add_donation_table

Revision ID: dcd1d0b6c346
Revises: 850f324dd0cb
Create Date: 2025-06-24 02:55:45.718386

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dcd1d0b6c346"
down_revision = "850f324dd0cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_challenge_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("associated_skill_id", sa.Integer(), nullable=True),
        sa.Column(
            "challenge_type",
            sa.Enum(
                "TEXT_RESPONSE",
                "PHOTO_UPLOAD",
                "CHECKBOX_COMPLETION",
                name="challengetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevel"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "donation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("transaction_id", sa.String(length=255), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_table(
        "user_challenge_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_template_id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("user_response", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING_REVIEW", "COMPLETED", "FAILED", name="completionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_template_id"],
            ["practice_challenge_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_challenge_completions")
    op.drop_table("donation")
    op.drop_table("practice_challenge_templates")
    # ### end Alembic commands ###
